#!/usr/bin/env node
/**
 * Stop hook (strict): runs only `npm run typecheck` on stop. On a real failure
 * it blocks so Claude fixes it before
 * finishing. Generated by aia-harness — fail-open on infra: a missing runtime
 * or command never blocks. Re-run /aia-harness:doctor to audit.
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { sessionScratchDir } from "./session-scratch.mjs";

const COMMANDS = [{ label: "typecheck", cmd: "npm run typecheck" }];
const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const LINTABLE = /\.(js|jsx|ts|tsx|mjs|cjs|vue|svelte|php)$/;

let event = {};
try {
  event = JSON.parse(fs.readFileSync(0, "utf8") || "{}");
} catch {
  process.exit(0);
}
const sessionId = typeof event?.session_id === "string" ? event.session_id : "nosession";

function flagFile() {
  return path.join(sessionScratchDir(sessionId), "files-changed");
}
function clearFlag() {
  try {
    fs.rmSync(flagFile(), { force: true });
  } catch {
    /* ignore */
  }
}
function approve() {
  process.stdout.write(JSON.stringify({ decision: "approve" }));
  process.exit(0);
}

// Anti-loop: a stop already triggered by a previous block must be allowed.
if (event?.stop_hook_active) {
  clearFlag();
  approve();
}

const flag = flagFile();
if (!fs.existsSync(flag)) approve(); // session changed nothing

let changed = "";
try {
  changed = fs.readFileSync(flag, "utf8");
} catch {
  approve();
}
const hasLintable = changed.split("\n").some(p => LINTABLE.test(p.trim()));
if (!hasLintable) {
  clearFlag();
  approve();
}

// Ensure the active node's dir (nvm/fnm/system node) is on PATH for the run.
// process.execPath is always the actual running binary — works with any node manager.
const binDir = path.dirname(process.execPath);
const env = Object.assign({}, process.env, {
  PATH: binDir + path.delimiter + (process.env.PATH || "")
});

const execDir = (event && typeof event.cwd === "string" && event.cwd) || projectDir;
const failures = [];
for (const entry of COMMANDS) {
  try {
    execSync(entry.cmd, {
      cwd: execDir,
      env: env,
      timeout: 120000,
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"]
    });
  } catch (err) {
    const stderrText = err.stderr ? err.stderr.toString() : "";
    // ENOENT / exit 127 = command or runtime missing -> infra, fail open.
    if (err.code === "ENOENT" || err.status === 127) continue;
    // Windows cmd.exe has no POSIX exit 127 for a missing command; it exits 1
    // with this message instead. ponytail: English-locale match only, switch
    // to a PATH pre-check if non-English Windows needs support.
    if (
      process.platform === "win32" &&
      /is not recognized as an internal or external command/i.test(stderrText)
    )
      continue;
    const out = ((err.stdout ? err.stdout.toString() : "") + stderrText).trim();
    failures.push({
      label: entry.label,
      cmd: entry.cmd,
      out: out || err.message || `${entry.label} failed`
    });
  }
}

if (failures.length === 0) {
  clearFlag();
  approve();
}

let lines = [];
for (const f of failures) {
  lines.push(`=== ${f.label} (${f.cmd}) failed ===`);
  lines = lines.concat(f.out.split("\n"));
  lines.push("");
}
const excerpt = lines.slice(0, 80).join("\n");
const truncated = lines.length > 80 ? `\n...(${lines.length - 80} more lines)` : "";

// Stop schema: top-level decision + reason only (no hookSpecificOutput channel).
process.stdout.write(
  JSON.stringify({
    decision: "block",
    reason: `Fix all typecheck errors below before finishing.\n\n${excerpt}${truncated}`
  })
);
process.exit(0);
